#%RAML 1.0 DataType
type: object
properties:
  id: string
  userId: string
  user?:
    type: object
    properties:
      id: string
      uuid: string
      externalId: string
      dataSourceId: string
      userName: string
      studentId: string
      educationLevel: string
      gender: string
      pronouns: string
      birthDate: datetime
      created: datetime
      modified: datetime
      lastLogin: datetime
      institutionRoleIds: object
      systemRoleIds: object
      availability:
        type: object
        properties:
          available: string
