#%RAML 1.0 DataType
type: object
properties:
  results:
    type: array
    items:
      type: object
      properties:
        id: string
        userId: string
        courseRoleId: string
        created: datetime
        modified: datetime
        availability?:
          type: object
          properties:
            available:
              type: string
              enum: [Yes, No, Disabled]
        dataSourceId?: string
        lastAccessed?: datetime
        user?:
          type: object
          properties:
            id: string
            userName?: string
            studentId?: string
            externalId?: string
  paging?:
    type: object
    properties:
      nextPage?: string
