#%RAML 1.0 DataType
type: object
properties:
  childCourseId?: string
  dataSourceId?: string
  availability?:
    type: object
    properties:
      available: string
  courseRoleId?: string
  displayOrder?: integer
