#%RAML 1.0 DataType
type: object
properties:
  id: string
  uuid: string
  externalId: string
  dataSourceId: string
  userName: string
  studentId: string
  educationLevel:
    type: string
    enum: [K8, K12, Undergraduate, Graduate, Other]
    example: K8
  gender:
    type: string
    enum: [Male, Female, Other]
    example: Female
  pronouns: string
  birthDate: datetime
  created: datetime
  modified: datetime
  lastLogin: datetime
  institutionRoleIds:
    type: array
    items: string
  systemRoleIds:
    type: array
    items: string
    example: [SystemAdmin]
  availability:
    type: object
    properties:
      available:
        type: string
        enum: [Yes, No, Disabled]
        example: Yes
  name:
    type: object
    properties:
      given: string
      family: string
      middle: string
      other: string
      suffix: string
      title: string
      preferredDisplayName: string
  job:
    type: object
    properties:
      title: string
      department: string
      company: string
  contact:
    type: object
    properties:
      homePhone: string
      mobilePhone: string
      businessPhone: string
      businessFax: string
      email: string
      institutionEmail: string
      webPage: string
  address:
    type: object
    properties:
      street1: string
      street2: string
      city: string
      state: string
      zipCode: string
      country: string
  locale:
    type: object
    properties:
      id: string
      calendar:
        type: string
        enum: [Gregorian, Lunar, Other]
        example: Gregorian
      firstDayOfWeek:
        type: string
        enum: [Sunday, Monday, Saturday]
        example: Sunday
  avatar:
    type: object
    properties:
      viewUrl: string
      source:
        type: string
        enum: [Default, Custom]
        example: Default
      uploadId: string
      resourceId: string
  pronunciation: string
  nodes:
    type: array
    items:
      type: object
      properties:
        id: string
        externalId: string
        title: string
        description: string
        parentId: string
  pronunciationAudio:
    type: object
    properties:
      viewUrl: string
      uploadId: string
