#%RAML 1.0 DataType
type: object
properties:
  results:
    type: array
    items:
      type: object
      properties:
        id: integer
        meetingId: string
        userId: string
        status: string
        modifiedByUserId: string
        createdTime: datetime
        modifiedTime: datetime
  paging:
    type: object
    properties:
      nextPage: string
