#%RAML 1.0 DataType
type: object
properties:
  externalId?: string
  dataSourceId?: string
  name?: string
  description?: string
  allowGuests?: boolean
  allowObservers?: boolean
  closedComplete?: boolean
  termId?: string
  availability?:
    type: object
    properties:
      available?: string
      duration?:
        type: object
        properties:
          type?: string
          start?: datetime
          end?: datetime
          daysOfUse?: integer
  enrollment?:
    type: object
    properties:
      type?: string
      start?: datetime
      end?: datetime
      accessCode?: string
  locale?:
    type: object
    properties:
      id?: string
      force?: boolean
